global:
  scrape_interval:     30s # Set the scrape interval to every 30 seconds
  evaluation_interval: 30s # Evaluate rules every 30 seconds

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
    
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']    
